-- create default table space

CREATE TABLESPACE FUGERIT_DATA  DATAFILE 'FUGERIT_DATA.dbf';

-- user creation
CREATE USER FUGERIT IDENTIFIED BY FUGERIT DEFAULT TABLESPACE FUGERIT_DATA;
GRANT UNLIMITED TABLESPACE TO FUGERIT;
GRANT ALL PRIVILEGES TO FUGERIT;
GRANT CREATE SESSION TO FUGERIT;